<a href="https://colab.research.google.com/github/Suma-Marri/DataPrep_Assignment2/blob/main/DataPrep_Assignemnt2_Problem3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install google.colab
!pip install linearmodels

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/DPFONAL_1.csv")
df = df.dropna(axis= 0, how='any', subset=['marital'])
df.head()

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (134) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


rev_Mean  mou_Mean  totmrc_Mean  da_Mean  ovrmou_Mean  ovrrev_Mean  \
0   76.9800      0.00      86.9800      0.0          0.0        0.000   
1   30.2700     28.25      30.0000      0.0          0.0        0.000   
2   46.1025    203.00      37.6575      0.0         30.5       10.675   
3   16.9900      3.25      16.9900      0.0          0.0        0.000   
4   40.0700    270.00      50.0700      0.0          0.0        0.000   

   vceovr_Mean  datovr_Mean  roam_Mean  rev_Range  ...  kid0_2  kid3_5  \
0        0.000          0.0        0.0       0.00  ...       U       U   
1        0.000          0.0        0.0       0.54  ...       U       U   
2       10.675          0.0        0.0      31.87  ...       U       U   
3        0.000          0.0        0.0       0.00  ...       U       U   
4        0.000          0.0        0.0       0.32  ...       U       U   

   kid6_10  kid11_15  kid16_17  creditcd  car_buy  retdays  eqpdays  \
0        U         U         U         N  UNKNOWN      NaN      NaN   
1        U         U         Y         Y  UNKNOWN      NaN    566.0   
2        Y         Y         U         Y      New      NaN      7.0   
3        U         U         U         Y      New      NaN   1287.0   
4        U         U         U         Y      New      NaN   1131.0   

   Customer_ID  
0      1077200  
1      1032004  
2      1003956  
3      1002348  
4      1003683  

[5 rows x 173 columns]

In [ ]:
df.groupby('marital').mean()

rev_Mean    mou_Mean  totmrc_Mean   da_Mean  ovrmou_Mean  \
marital                                                              
A        57.188450  457.401855    45.113339  0.941499    39.236780   
B        61.661802  551.311597    48.081553  1.040501    44.203778   
M        52.173508  405.132434    42.881550  0.740874    32.062420   
S        60.109386  538.743557    46.505380  0.872373    42.810466   
U        62.672928  589.179259    48.318299  0.977068    46.629686   

         ovrrev_Mean  vceovr_Mean  datovr_Mean  roam_Mean  rev_Range  ...  \
marital                                                               ...   
A          12.757927    12.585329     0.172489   1.622567  41.482565  ...   
B          14.334368    14.045042     0.284047   1.183584  46.295328  ...   
M          10.495626    10.304785     0.189628   1.155373  34.217745  ...   
S          14.312681    14.010973     0.296795   1.348676  47.471232  ...   
U          15.507066    15.186949     0.316968   1.348238  51.230431  ...   

              age1       age2    adults    income  numbcars  forgntvl  \
marital                                                                 
A        42.146658  40.576682  3.001514  5.790245  1.571912  0.002379   
B        29.182709   0.000000  1.000000  5.082934  1.379852  0.002177   
M        46.431997  39.057306  3.085009  6.480420  1.638403  0.121421   
S        37.123485  19.434470  2.342424  4.960262  1.511773  0.084407   
U        13.976533   7.442538  2.198563  5.594456  1.520917  0.010559   

            educ1     retdays     eqpdays   Customer_ID  
marital                                                  
A        1.723404  245.282051  411.148605  1.046452e+06  
B        1.718750  209.879433  385.453429  1.048707e+06  
M        1.891918  215.406452  433.797979  1.046845e+06  
S        1.787465  218.455587  386.583207  1.048704e+06  
U        1.980636  219.348599  359.184438  1.053725e+06  

[5 rows x 138 columns]

In [ ]:
df['marital'].replace(['U', 'M', 'S', 'B', 'A'], [1, 2, 3, 4, 5], inplace=True)

In [ ]:
from statsmodels.formula.api import ols
from patsy.contrasts import Treatment
from patsy.contrasts import Diff

In [ ]:
levels = [1,2,3,4,5]

In [ ]:
pd.get_dummies(df.marital.values, drop_first=False)

1  2  3  4  5
0      1  0  0  0  0
1      0  1  0  0  0
2      0  1  0  0  0
3      1  0  0  0  0
4      0  0  1  0  0
...   .. .. .. .. ..
88414  0  0  0  0  1
88415  1  0  0  0  0
88416  0  1  0  0  0
88417  0  1  0  0  0
88418  0  0  1  0  0

[88419 rows x 5 columns]

In [ ]:
contrast = Diff().code_without_intercept(levels)

In [ ]:
print(contrast.matrix)

[[-0.8 -0.6 -0.4 -0.2]
 [ 0.2 -0.6 -0.4 -0.2]
 [ 0.2  0.4 -0.4 -0.2]
 [ 0.2  0.4  0.6 -0.2]
 [ 0.2  0.4  0.6  0.8]]


In [ ]:
mod = ols("rev_Mean ~ C(marital, Diff)", data=df)
res = mod.fit()
print(res.summary())

                            OLS Regression Results                            
Dep. Variable:               rev_Mean   R-squared:                       0.010
Model:                            OLS   Adj. R-squared:                  0.009
Method:                 Least Squares   F-statistic:                     211.8
Date:                Mon, 26 Sep 2022   Prob (F-statistic):          3.26e-181
Time:                        23:27:52   Log-Likelihood:            -4.6271e+05
No. Observations:               88102   AIC:                         9.254e+05
Df Residuals:                   88097   BIC:                         9.255e+05
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
Intercept                58.76